[package]
name = "project"
#build = "build.rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#anyhow = "1.0.72"
rodio = "0.17.1"
slint = "1.0.2"
#tray-item = "0.8.0"
#native-windows-gui = "1.0.12"
#native-windows-derive = "1.0.3" # Optional. Only if the derive macro is used.

[build-dependencies]
#windres = "*"
slint-build = "1.1.0"
reqwest = { version = "0.11.11", features = ["json", "cookies"] }
