import {
    ListView,ScrollView,VerticalBox
, GridBox} from "std-widgets.slint";
import { musiclistdata } from "list.slint";
export struct CardList {
    music:string,user:string,date:string,id:string
}

export component MusicCard {
    in-out property <musiclistdata> othermusic;
    in-out property <string> user;
    in-out property <string> music;
    in-out property <string> date;
    in-out property <string> id;
    callback choose-music();
    Rectangle{
        Image{
            y:2px;
            x:2px;
            image-rendering: pixelated;
            source: @image-url("../assets/icon/avatar.png");
            width: 30px;
        }
        TouchArea {
            clicked => {othermusic={name:music,user:user,date:date,id:id};choose-music()}
        }
        Text{
            y:2px;
            x:40px;
            font-size: 20px;
            text: user;
        }
        Text{
            y:40px;
            x:0px;
            font-size: 20px;
            text: music;
        }
        Text{
            y:70px;
            x:0px;
            font-size: 15px;
            text: date;
        }
    }

}
export component MusicCardList {
    in-out property <[{cards:[CardList]}]> cards;
    in-out property <musiclistdata> othermusic;
    callback choose-music();
    ListView {
            for card in cards:HorizontalLayout{
                padding: 10px;
                spacing: 10px;
                height: 120px;
                for tcard in card.cards:MusicCard{
                user:tcard.user;
                music:tcard.music;
                date:tcard.date;
                id:tcard.id;
                choose-music=>{othermusic=self.othermusic;choose-music()}
            }}
        
    }
}
