import { StandardListView,ListView  } from "std-widgets.slint";
import {
    ComboBox, VerticalBox, HorizontalBox, GridBox, Button,
    LineEdit, ListView, GroupBox, CheckBox, TabWidget,StandardTableView
} from "std-widgets.slint";

export struct musiclistdata {
    user:string,
    name:string,
    date:string,
    id:string,
    public:bool
}

component Pane inherits Rectangle {
    // capture all clicks
    TouchArea {}
}

export global ListValue {

}
 export component MusicList inherits Pane {
    //callback back <=> back_btn.clicked;
    callback choose-music(musiclistdata);
    callback close();
    in-out property <musiclistdata>music-choosed;
    in-out property <bool> is-playing;
    in-out property <[{user:string,name:string,date:string,public:bool,id:string}]> musiclist:[
        { user:"2146265126",name: "ギターと孤独と蒼い惑星",date:"11"},
        { name: "Let_me_do_it_for_u"},
        { name: "桜高軽音部 - ふわふわ時間 (Single Ver.)"},
        { name: "めありー,Orangestar - Alice in 冷凍庫"},
        { name: "結束バンド - Distortion!!"},
        { name: "結束バンド - 青春コンプレックス"},
        { name: "大橋卓弥 - ありがとう"},
        { name: "さんひ - ほろよい"},
    ];
    width: 450px;
    height: 500px;

    VerticalBox {
        ListView{
            for data in  musiclist: Rectangle {
                background: #000000;
                listtouch:=TouchArea{
                    clicked => {root.music-choosed={id:data.id};root.choose-music(
                        {id:data.id}
                        );close();is-playing=true;}
                }
                height: 30px;
                width: parent.width;
                function textss(text:string) ->string{
                        
                    if(data.public){
                        
                        return text+" 上传者:"+data.user+" 公开"+" 日期:"+data.date;
                    }
                    else{
                        return text+"  私有"+" 日期:"+data.date;
                    }

                    
                    return text;
                }
                Text {

                    x: 0;
                    text: textss(data.name);

                    color: listtouch.has-hover?#8d8d8d:#ffffff;
                    animate color { 
                        duration:200ms;
                     }
                    
                }
        }
    }
}
}