
import { setting } from "setting.slint";
import { list,BuildingPane } from "list.slint";
import { user-main } from "user.slint";
import { homepage } from "homepage.slint";
import { MusicLib } from "MusicLib.slint";
import { SideBar } from "SideBar.slint";
//import { BorderlessWindow } from "borderless-window.slint";
import {
    ComboBox, VerticalBox, HorizontalBox, GridBox, Button,
    LineEdit, ListView, GroupBox, CheckBox, TabWidget,
    AboutSlint
} from "std-widgets.slint";

import "../assets/fonts/fangzheng.ttf";
export component Select inherits ComboBox {

        y: 30px;
        width: self.preferred-width;
        height: self.preferred-height;

        current-value: "first";
    
}
export component Close {
    Image {
        source: @image-url("../assets/icon/xmark.svg");
        width: 15px;
        //colorize: area.has-hover ? #29292984 : #ffffff;
        colorize: #ffffff;

        // animate colorize {
        //     duration: 250ms;
        // }
        
    }
    
}

export component player{
    //callback music_play();
    
    Rectangle {
        background: #4d4d4d81;
    }
    Image {
        ListArea := TouchArea {clicked => {values.click_audio1();}}
        source: @image-url("../assets/icon/music_list.svg");

        width: 40px;
        y: parent.height/3.2;
        x: 40px;

        //colorize: ListArea.has-hover ? #cf2727 : #ffffff;
        colorize: #ffffff;
        animate colorize {
            duration: 250ms;
        }


    }
    Image {
        visible: !values.is-playing;
        PlayerArea := TouchArea { clicked => {
            values.music_play();
            values.is-playing=true;
            values.click_audio();
        
        }}
        source: @image-url("../assets/icon/play.svg");
        width: 30px;
        x:parent.width/2;
        y:parent.height/3.5;
        
        //colorize: ListArea.has-hover ? #cf2727 : #ffffff;
        colorize: #ffffff;
        animate colorize {
            duration: 250ms;
        }


    }
    Image {
        visible: values.is-playing;
        PauseArea := TouchArea { clicked => {
            values.music-pause();
            values.is-playing=false;
            values.click_audio();
        
        }}
        source: @image-url("../assets/icon/pause.svg");
        width: 25px;
        x:parent.width/2;
        y:parent.height/3.6;
        
        //colorize: ListArea.has-hover ? #cf2727 : #ffffff;
        colorize: #ffffff;
        animate colorize {
            duration: 250ms;
        }


    }

}

export component search{
    
    area := TouchArea {}
    Rectangle {
        background: #0c325281;
    }
    Image {
        source: @image-url("../assets/icon/search.svg");
        width: 15px;
        y: 15px;
        x: 15px;
        //colorize: area.has-hover ? #29292984 : #ffffff;
        colorize: #ffffff;

        // animate colorize {
        //     duration: 250ms;
        // }
        
    }
    TextInput {
        font-family: "方正少儿简体";
        font-size: 25px;
        width:  parent.width;
        height: parent.height;
        x:parent.width/5;
        y:parent.height/6;
    }


}

export global values {
    in-out property <bool> pane-visible:true;
    in-out property <bool> is-playing: false;
    in-out property <string> url:"https://space.bilibili.com/485727024?spm_id_from=333.1007.0.0";

    property <bool> drag-area-pressed: false;
    // 记录按下的位置
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    
    callback music_play();
    callback click_audio();
    callback click_audio1();
    callback music_pause();
    callback close-window();
    callback move-window(length, length);

}

export component AppWindow inherits Window {
    
    in-out property <bool> pane-visible:true;
    in-out property <bool> is-playing: false;
    in-out property <string> url <=> values.url;
    no-frame: true;
    property <bool> drag-area-pressed: false;
    // 记录按下的位置
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    
    callback music_play<=> values.music_play;
    callback click_audio<=> values.click_audio;
    callback click_audio1<=> values.click_audio1;
    callback open_the_url(string);
    callback music_pause<=> values.music_pause;
    callback close-window();
    callback move-window(length, length);
    in property <string> user_name:"pingfanh";
    in property <string> user_intro:"开发人员";
    in property <string> user_gender:"男";
    in property <string> user_age:"15";
    in property <int> user_music_number:114;

    
    title:"P-layer";
    Rectangle {
        x:0;
        y:0;
        height: 30px;
        width: parent.width;
        background: #5f121200;
        TouchArea {
            moved => {
                //根据移动的偏移量，设置窗口位置
                move-window(self.mouse-x - drag-area-down-x, self.mouse-y - drag-area-down-y);
            }
            pointer-event(ev) => {
                drag-area-pressed = ev.kind == PointerEventKind.down;
                drag-area-down-x = self.mouse-x;
                drag-area-down-y = self.mouse-y;
            }
        }
    }
    icon: @image-url("../assets/icon/icon.png");
    preferred-width: 656px;
    preferred-height: 670px;
    callback showsetting();
    default-font-family: "方正少儿简体";
    Text {
        color: #3b3b3b;
        text: "CopyRightⒸPingfanH";
        font-size: 15px;
        y:parent.height/37;
        x:parent.width -229px;
    }
    Close{
        y:parent.height/37;
        x:parent.width -229px;
    
    }
    Button {
        //icon: @image-url("../assets/icon/xmark.svg");
        
        y:parent.height/40;
        x:parent.width -50px;
         width: 25px;
         height: 25px;
        
        clicked => {
        click_audio1();
        close-window();
        }
    }

    HorizontalLayout {
        side-bar := SideBar {

            title: @tr("P-layer");
            model: [@tr("Menu" => "主页"), @tr("Menu" => "音乐库"), @tr("Menu" => "我的"), @tr("Menu" => "设置")];
            click-audio=>{root.click-audio()}
        }

        if(side-bar.current-item == 0) : homepage {
            width: 500px;
            open-url=>{root.open_the_url(url)}
        
        }
        if(side-bar.current-item == 1) : MusicLib {width: 500px;}
        if(side-bar.current-item == 2) : user-main {
            width: 500px;
            user-name:root.user_name;
            user-intro:root.user_intro;
            user-gender:root.user_gender;
            user-age:root.user_age;
            user-music-number:root.user_music_number;
            
        }
        if(side-bar.current-item == 3) : setting {width: 500px;}
        // if(side-bar.current-item == 4) : AboutPage {}
    }

    
    // TabWidget {
        //     // hide the widgets from the tab focus handler when covered:
        //     visible: pane-visible;
        //     width: parent.width;
        //     y:30px;
        //     Tab {
        //         title: "主页";
        //         homepage{}
        //     }

        //     Tab {
        //         title: "音乐库";

        //     }

        //     Tab {
        //         title: "我的";
        //         user-main{
                    
        //         }
        //     }

        //     Tab {
        //         title: "设置";
        //         setting{
        //             // preferred-width: parent.width;
        //             // preferred-height: parent.height;
        //         }
        //     }
        // }
        player{
            x:20px;
            y:parent.height -130px;
            preferred-width: parent.width -37px;
            preferred-height: 110px;
            
        }


    // Rectangle {
    //     background: @linear-gradient(125deg,#130c27 90%, #0f0c16 100%, #1c123a 100%,#1f1441 100%, #180446 100%);
    // }
    
    // list{
    //     x:100px;
    //     y: parent.height/2.3;
    // }
    // Image {
    //     CloseArea := TouchArea {}
    //     source: @image-url("../assets/icon/xmark.svg");
    //     width: 25px;
    //     y: 20px;
    //     x: parent.width -60px;
        
    //    //colorize: CloseArea.has-hover ? #000000 : #dfdbdb;
    //    colorize: #dfdbdb;


    //     animate colorize {

    //         duration: 100ms;
    //     }
        
        
    // }
    // Image {
    //     SettingArea := TouchArea {clicked => { popup.show(); }}
    //     source: @image-url("../assets/icon/setting.svg");
    //     width: 25px;
    //     y: 22px;
    //     x: parent.width -120px;
    //     //colorize: SettingArea.has-hover ? #cf2727 : #ffffff;
    //     colorize: #dfdbdb;
    //     animate colorize {
    //         duration: 100ms;
    //     }
        

    // }
    
    // popup := PopupWindow {
    //     x: 100px;
    //     y: parent.height/8;
    //     height: parent.height;
    //     width: parent.width/2;
    //     Rectangle {
    //         height:100%; 
    //         width: 100%; 
    //         background: #ff0000; 
    //     }
    // }
    // Image {
    //     UserArea := TouchArea {}
    //     source: @image-url("../assets/icon/user.svg");
    //     width: 25px;
    //     y: 22px;
    //     x: parent.width -180px;
    //     //colorize: UserArea.has-hover ? #cf2727 : #ffffff;
        
    //     colorize: #dfdbdb;
    //     animate colorize {
    //         duration: 100ms;
    //     }

    // }
    // search{
    //     y: 17px;
    //     width: parent.width/5;
    //     height: 44px;
    // }
    // player{
    //     y: parent.height -100px;
    //     width: parent.width -15px;
    //     height: 90px;
    // }

}
